
apiVersion: v1 
kind: Service
metadata: 
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    app: backend
    tier: backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080
